version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: "kpmp-user-mongo"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - "kpmp-mongo:/usr/data/db"
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

volumes:
  kpmp-mongo:

networks: 
  default:
    name: kpmp-user-portal