version: "3.7"
services:

  portal-mongodb:
    build:
      context: ./docker/mongodb
    env_file: ./.docker.env
    container_name: "kpmp-user-mongo"
    volumes:
      - "kpmp-mongo-data:/data/db"
    ports:
        - 27017:27017
    networks:
      local:
        aliases:
          - portal-mongodb
    command: mongod --logpath=/dev/null # --quiet

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: ./.docker.env
    environment:
      - FLASK_RUNNING_IN_DOCKER=true
    container_name: "kpmp-user-app"
    ports:
      - 5001:5001
    networks:
      local:
        aliases:
          - user-portal

volumes:
  kpmp-mongo-data:

networks: 
  local:
