version: "3.7"
services:

  portal-mongodb:
    image: mongo:latest 
    container_name: portal-mongodb
    volumes:
      - "kpmp-mongo-data:/data/db"
    ports:
        - 27018:27017
    networks:
      dataLake:
        aliases:
          - portal-mongodb
    command: mongod --logpath=/dev/null # --quiet

  portal-app:
    image: ${ENV_PORTAL_APP_CONTAINER} 
    environment:
      - FLASK_RUNNING_IN_DOCKER=true
    container_name: portal-app
    ports:
      - 5001:5001
    networks:
      dataLake:
        aliases:
          - user-portal

volumes:
  kpmp-mongo-data:

networks: 
  dataLake:
    external: true
