version: "3.7"
services:
  mongodb:
    build:
      context: ./docker/mongodb
    container_name: "kpmp-user-mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - "kpmp-mongo-data:/data/db"
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

volumes:
  kpmp-mongo-data:

networks: 
  default:
    name: kpmp-user-portal